### ISSUE TITLE
Stuck at Installation Wizard step 3 - Database

### ISSUE THREAD

**Issue by jeneeben** [craigk5n/webcalendar#430] opened 2023-10-18 06:14 UTC
Hi,
i am not able to go pass Step 3 in the installation wizard. After installting Database it is keep saying "This appears to be an upgrade..." and i need to "update Database". I am also not able to click on "Next" or display the required SQL.

I verified that all tables are created in the DB and also imported all tables using the tables-mysql.sql file. But it still won't allow me to go to the next step.

I am using PHP version 8.1.2

Thanks for your help,
Jeneeben

**Comment by craigk5n** [comment] 2023-10-20 19:15
Duplicate of (or closely related to) #431 
Rewrite of installer for v1.9.11 should fix this.  In the mean, time run the following SQL commands (some may not be necessary depending on what version you had before):

```
ALTER TABLE webcal_import ADD cal_check_date INT NULL;
ALTER TABLE webcal_import ADD cal_md5 VARCHAR(32) NULL DEFAULT NULL;
CREATE INDEX webcal_import_data_type ON webcal_import_data(cal_import_type);
CREATE INDEX webcal_import_data_ext_id ON webcal_import_data(cal_external_id);
ALTER TABLE webcal_user MODIFY cal_passwd VARCHAR(255);
update webcal_entry_categories SET cat_owner = '' WHERE cat_owner IS NULL;
ALTER TABLE webcal_entry_categories ADD PRIMARY KEY (cal_id, cat_id, cat_order, cat_owner);
```

That should fix the db.  If you keep getting redirected to the installer, update the version in the database:

```
update webcal_config set val_value = 'v1.9.10' where cal_setting = 'WEBCAL_PROGRAM_VERSION';
```

**Closed by craigk5n** 2023-10-20 19:15 UTC
