### ISSUE TITLE
"dbi_update_blob" is not implemented for mysqli

### ISSUE THREAD

**Issue by Flancandrin** [craigk5n/webcalendar#62] opened 2017-12-14 04:06 UTC
it says 

> Unfortunately, ""dbi_update_blob"" is not implemented for (mysqli).

**Comment by FranzGotsis** [comment] 2018-02-21 00:58
Once you use WebCalendar 1.2.9 or higher and you are running PHP 7.1.x the problem is no longer there. You can add comments that show up without problems.

**Comment by OvrClocked01** [comment] 2018-05-03 05:02
I am using Web Calendar 1.3.0  on PHP 7.1 w/ PHP-FPM on and I am still having the same issue:
`Unfortunately, ""dbi_update_blob"" is not implemented for (mysqli).`

Please let me know what I need to change. I have also removed magic quotes where-ever I could find them.

Also - Love the app, all else works great and is very useful. I look to donate to this project in the near future for the features it has provided me in business.

**Comment by craigk5n** [comment] 2018-07-13 14:34
Fixed with commit d48dd6850841eb551255df1bcc939ef228fa732d.

- Implement dbi_update_blob for mysqli
- Implement dbi_get_blob for for mysqli
- Affects usage of attachments and comments (which both use blobs)

**Closed by craigk5n** 2018-07-13 14:34 UTC
