### ISSUE TITLE
How to fix some erros

### ISSUE THREAD

**Issue by s33d3r** [craigk5n/webcalendar#92] opened 2018-06-01 02:48 UTC
Comment all lines in install/install_functions.php and install/index.php where set_magic_quotes_runtime appears.
Replace code in includes/formvars.php line 33:
from:
        $teststr = preg_replace ( "#(\\\x[0-9A-F]{2})#e",
          "chr(hexdec('\\1'))", $instr[$j] );
to:
$teststr = preg_replace_callback ( "#(\\\x[0-9A-F]{2})#",
          function ($m){ return chr(hexdec('0x'.$m[1]));}, $instr[$j] );

Not sure if it's the best solution but it did work.
The previous functions doesn't work in PHP 7.0
If I've done something wrong I'll gladly listen to you.

edit: seems that the second solution was already covered in issue #66 
edit2:I'll fork the code to make pull request, I'm still a git newbie

**Comment by FranzGotsis** [comment] 2018-07-14 13:22
I am the author of the issue #66 and as far as I can tell your solution as good as mine and based on my experience it works as intended.

But the current main line code (1.3.0) covers this solution already and the current code is very well documented. So I suggest you just download release 1.3.0 and use that, as there are a large number of improvements in the code.

kind regards
Franz Gotsis

**Comment by craigk5n** [comment] 2018-11-21 15:34
Fixed in the master branch with commit f2e1c00a86b6448146691d20e04444fe861caaf4.

**Closed by craigk5n** 2018-11-21 15:34 UTC
